env:
  browser: true

parser: babel-eslint

parserOptions:
  ecmaVersion": 6

extends: ['airbnb-base']

plugins: ['import']

rules:
  import/no-extraneous-dependencies: 0

# Global scoped method and vars
globals:
  __dirname: true
  require: true
  process: true
  ENV: true
  module: true
  $: true
