backend:
  name: git-gateway
  branch: master

media_folder: site/static/images
public_folder: /images

collections:
  - name: home
    label: 'Home Page'
    file: _index.md
    folder: site/content
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Subtitle, name: subtitle, widget: string }
      - { label: 'Main Image', name: image, widget: image }
      - { label: 'Sponsor Message', name: sponsor, widget: markdown }
      - { label: 'Latest News Message', name: news, widget: markdown }
      - { label: About, name: body, widget: markdown }
  - name: sponsors
    label: 'Sponsors'
    folder: 'site/content/sponsors'
    create: true
    delete: true
    fields:
      - { label: 'Name', name: 'title', widget: string }
      - { label: 'Logo', name: 'image', widget: image }
      - { label: 'Link', name: 'link', widget: string }
      - { label: 'Sort Priority', name: priority, widget: number, default: 0 }
      - { label: Type, name: type, widget: string, default: sponsor }
